name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 一般的なメトリクス（ヘッダー + 3Dカレンダー）
      - name: Calendar Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kuronomagi
          template: classic
          base: header
          base_indepth: yes
          config_timezone: Asia/Tokyo
          config_order: base.header, isocalendar, habits
          filename: calendar-metrics.svg
          config_output: svg
          output_action: overwrite
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # 3Dカレンダー
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # 言語統計（詳細版）
      - name: Language Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kuronomagi
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          filename: language-metrics.svg
          config_output: svg
          output_action: overwrite
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # 言語統計の詳細設定
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, lines
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_recent_categories: programming
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: kuronomagi/kuronomagi
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming, data, markup
          plugin_languages_ignored: "html, css"
