name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # リポジトリをチェックアウト（重要：既存ファイルの取得）
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Metricsを生成
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kuronomagi
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          filename: github-metrics.svg
          config_output: svg
          # 重要：上書きを許可
          output_action: overwrite
          committer_token: ${{ secrets.GITHUB_TOKEN }}